# SITE CONFIGURATION
title: cassioroos # your site title
author: cassioroos # You :P
description: > # Meta description of Homepage
    Esse blog tem como objetivo ajudar outros devs que estejam passando pelas mesmas coisas que ou
    incetivar o uso de novas tecnologias
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cassioroos.com"

# SEO PLUGIN
social:
  name: cassioroos
  links:
    - https://twitter.com/cassioroos
    - https://www.linkedin.com/in/cassioroos
    - https://github.com/CassioRoos

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  It's me, a Dev

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: cassio.roos@gmail.com # email for form submission

twitter_username: cassioroos
github_username:  cassioroos

disqus:
  shortname: cassioroos

google_analytics: UA-132045111-1
google_tag_manager: UA-132045111-1 

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
